import Head from "next/head";

export default function Header(props: { pageName: string }) {
  return (
    <Head>
      <title>Adam Zanon | {props.pageName}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
