import Head from "next/head";

export default function Header(props: { page_name: string }) {
  return (
    <Head>
      <title>Adam Zanon | {props.page_name}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
